# Created with WinGet Releaser using komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Odamex.Odamex
PackageVersion: 11.4.0
PackageLocale: en-US
Publisher: Odamex
PublisherUrl: https://odamex.net/
PublisherSupportUrl: https://github.com/odamex/odamex/issues
PrivacyUrl: https://odamex.net/privacy
PackageName: Odamex
PackageUrl: https://odamex.net/
License: GPL-2.0
LicenseUrl: https://github.com/electricbrass/odamex/blob/HEAD/LICENSE
ShortDescription: Multiplayer-oriented source port for Doom
Tags:
- doom
- game
- multiplayer
ReleaseNotesUrl: https://github.com/electricbrass/odamex/releases/tag/11.4.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
